### ISSUE TITLE
Regions vocabulary

### ISSUE THREAD

**Issue by heroldn** [ACDguide/invenioClim#5]
I've never done a search by region so take this with a grain of salt but not sure how useful recording this would be. And would a station located with lat/lon in Australia be double tagged to the "Australia" region? Would users have to do this double tagging (and if so then it basically becomes an unreliable search filter)? Not knowing any better I'd recommend removing this as a filter.

**Comment by paolap** [comment]
Thanks for the input, I have lots of doubts about this too actually, on a side I think users might do queries by region but then as you pointed out is hard to get really inclusive results as if you're looking for Australia data anything global is also ok. I'm happy to remove it but as we don't have a good spatial boundaries option yet I would also like to hear other opinions.
A potential solution is to use limited tags, so "global", "Australia-only" and a few others trying to anticipate the most common region-based queries. Rather than trying to be inclusive.
