### ISSUE TITLE
Small confusions after idealized model entry

### ISSUE THREAD

**Issue by paigem** [ACDguide/invenioClim#9]
I just added an [entry](https://oneclimate.dmponline.cloud.edu.au/records/6fh9g-4k635) for an idealized model that I used in my PhD. Because this is an idealized model and so built around the code (not the model output), I have a points of confusion to bring up. Some may require their own issue, but some may be simple answers, so I'm adding them all in a single issue for now:

- I wasn't sure what a "contributor" is. The model code is on GitHub and so there have been several contributors from a code-on-GitHub sense, so I'm not clear what counts as being a contributor in the OneClimate sense.
- I am still a bit confused by the `Dates` fields. There are several different places to include relevant dates (e.g. publication, updates, timespan of model, ...). The first instance of the publication date is unclear to me - is this when the code was first published? Or the newest version released? I ended up going with the date of first publication, then adding the newest version release as `Date Updated`.
- Should the DOI provided by this entry on OneClimate be the same as for the original paper publication? Or should it have its own? (I'm not very familiar with DOIs yet, so this could be a simple answer for those that know more!)
- Minor comment: some of the input options seem to have a red star denoting "required", when they are apparently not required (i.e. I was able to publish without them!)
- Would it make sense to upload the model guide to this OneClimate entry? If so, is there a place to upload such documents or perhaps just add a link? (Maybe I missed something here!)
- Are most of our entries going to be metadata only? If so, I wonder if we could change the default so that it assumes a metadata entry? The checkbox for a metadata entry isn't super obvious (I didn't notice until I got an error message trying to save).

**Comment by paolap** [comment]
Thanks for the super useful comments.
I think rather than answer everything here I'll use them for the guidance for contributors. So we have a central place where contributors can clarify find answers to similar questions.
Said so I'll ad something about the last 2 points and the doi, as they can have the biggest impact.

- you can upload the model guide as a file as we can potentially have files associated to a record. Even if we are not loading the data itself, we can upload reviews, notebooks, documents etc associated to the data. 
- if the document you are talking about is already available online elsewhere then just addicting a link to related information is also fine
- keep in mind than once you published a record is currently impossible to add/remove files so you need to create a new version. 

DOI

You should list the DOI of the resource you are describing if it exists already.
So in your case if the original paper publication is not just a reference but it is what you are describing then you should use its DOI.

As currently we have the DOI enabled it always expects a DOI to be already present or it will try to produce one.
So if a record doesn't have a DOI (as for a data portal) what you want to do is to give it a fake one using "10.1234567/<randomid>"
All DOIs starting with "10.1234567/" will be ignored and not displayed once the record is published. In this way we can avoid for a DOI to be produced and we have control on we displayed DOIs only when they're legitimate.

When you create a new version for. a record it will expect a new DOI, that can be an issue if we want to add related files after publishing. As the actual DOI is not changing. This behaviour might change in the future but I'm also testing another workaround  today
